---
output:
  officedown::rdocx_document:
    toc: no
---

```{r,echo=F,warning=F,message=F}

#Load libraries
require(flextable)
require(officer)
setwd('..')
source('clean_data.R')

carn_test <- wilcox.test(Froh~carnivore, data=all_data)
mig_test <- wilcox.test(Froh~migrates, data=all_data)
repro_test <- cor.test(all_data$Froh, all_data$repro, method='spearman')
```

**Table X.** Output from nonparametric tests for relationships between F~ROH~ and covariates. 

```{r,echo=F,message=F,warning=F}

params <- c('Diet = Carnivore', 'Migrates = yes', 'Repro capacity')
tests <- c('Wilcox','Wilcox','Spearman Rank-sum')
stat <- c(round(c(carn_test$statistic, mig_test$statistic)),round(repro_test$estimate,3))
pval_raw <- c(carn_test$p.value, mig_test$p.value, repro_test$p.value)

pvals <- as.character(round(pval_raw,3))
pvals <- paste0(pvals)
pvals[which(pvals=='0')] <- '< 0.001'

tab <- as.data.frame(cbind(params,tests,stat,pvals))
names(tab) <- c('Parameter','Test','Statistic','P-value')
row.names(tab) <- NULL

f <- flextable(as.data.frame(tab))
f <- theme_vanilla(f)
f <- autofit(f)
#  f <- align(f, j = c(4,7), align = "right", part = "all")
#  f <- align(f, i = 1, align = 'center', part = "header")

f
```
