Ne_period_analysis.html: Ne_period_analysis.Rmd
	Rscript -e "rmarkdown::render('Ne_period_analysis.Rmd')"

analysis_new.html: analysis_new.Rmd
	Rscript -e "rmarkdown::render('analysis_new.Rmd')"

stan_plots.html: stan_plots.Rmd
	Rscript -e "rmarkdown::render('stan_plots.Rmd')"

het_avg_Ne_analysis.html: het_avg_Ne_analysis.Rmd
	Rscript -e "rmarkdown::render('het_avg_Ne_analysis.Rmd')"
